### ISSUE TITLE
Please add a beta version number or similar

### ISSUE THREAD

**Issue by surfdado** [vedderb/vesc_tool#109]
There've been close to 10 different beta releases of the VESC Tool since the 5.1/2.06 release. Unfortunately the version number has always been the same. 

Please add an additional revision/beta-version/git-commit or other ID that gets displayed in the About dialog of the VESC tool.

Thank you!

**Comment by vedderb** [comment]
I agree, will add that to the next dev version. Leaving this issue open until then.

**Comment by surfdado** [comment]
I don't know if you can see this comment given that the issue is closed now, but is it just me or is the test version in the about dialog always 1 ? It would be nice if it instead matched the beta number in the firmware...
