### ISSUE TITLE
Parameter Editor doesn't save any changes

### ISSUE THREAD

**Issue by Peemouse** [vedderb/vesc_tool#11]
Hi,

After changes in parameter editor (app, motor or info), I apply, see the green highlighted message telling me that the xml has been saved.
But if I close and reopen the parameter editor, no changes have been taken into account.

**Comment by ufechner7** [comment]
Well, you need to load the XML file explicitly. I don't think that this is a bug, but the current behaviour should be better documented.

**Comment by vedderb** [comment]
That is the expected behavior. I'm working on on development and contribution documentation, as well as documentation on the communication interface, but it will take a bit of time.
