### ISSUE TITLE
Setting input ADC/ADC2 throttle/brake input is incorrectly represented

### ISSUE THREAD

**Issue by albfan** [vedderb/vesc_tool#110]
Setting an VESC with a throttle (ADC) and a brake (ADC2) input wizard seems confusing.

In "Current Reverse ..." modes throttle is suppossed to have a center position (accelerating on forward and braking or going back on backward) and "Current No Reverse ..." modes the input is linear (start position do nothing and max position accelerates or brakes at maximum) but they seem mixed.

- Off (All input disabled/greyed as expected):

    ![Captura de pantalla de 2021-01-11 02-14-21](https://user-images.githubusercontent.com/220968/104141110-537fc300-53b5-11eb-9daf-b37951d04b72.png)

- Current Reverse Center (this looks correct):

    ![Captura de pantalla de 2021-01-11 02-14-57](https://user-images.githubusercontent.com/220968/104141109-52e72c80-53b5-11eb-9148-734f25707f0b.png)

- Current No Reverse Brake Center (shouldn't brake be greyed? and throttle have a center?):
    > Current control. The output is off when the input is centered.  Input less than center brakes until the motor stops, but not further.
    
    ![Captura de pantalla de 2021-01-11 02-16-25](https://user-images.githubusercontent.com/220968/104141105-511d6900-53b5-11eb-9c87-f64c4ffde5b4.png)

    https://user-images.githubusercontent.com/220968/104141117-61354880-53b5-11eb-9adc-177a19b33acc.mp4

- Current No Reverse Brake ADC2 (ADC shows an incorrect center input, and ADC2 is wrongly disabled):

    ![Captura de pantalla de 2021-01-11 02-16-06](https://user-images.githubusercontent.com/220968/104141106-51b5ff80-53b5-11eb-9f94-dd12dc9bb57c.png)

    https://user-images.githubusercontent.com/220968/104141114-60041b80-53b5-11eb-8f1f-83102f28d967.mp4

- Current Reverse Button Brake Center (shouldn't current have a center position?)

    > Current control with a button for reversing throttle. The output is off when the input is centered.  Input less than center brakes until the motor stops, but not further.

    ![Captura de pantalla de 2021-01-11 02-15-11](https://user-images.githubusercontent.com/220968/104141108-52e72c80-53b5-11eb-8113-c4afc17f056e.png)

After select any of them, next page sets always "Current" as control type:

https://user-images.githubusercontent.com/220968/104141119-61cddf00-53b5-11eb-8d4c-1a0744d58e70.mp4

In this page, the control type behaves as expected, with "Current No Reverse Brake ADC2" being the correct choose for two separate inputs to control acceleration and brake.

VESC tool is 2.06

![Captura de pantalla de 2021-01-11 02-54-46](https://user-images.githubusercontent.com/220968/104141781-b9ba1500-53b8-11eb-9853-872b96b792f7.png)

Workaround:

- Use "Current Reverse Button Brake Center" to setup min/max voltage for ADC and ADC2
- Go to next page
- "Current" mode is selected.
- Check that "Current No Reverse Brake Center" do not use input from ADC2 as expected, accelerates presssing throttle on ADC and brakes when throttle is not pressed (pass the center I guess).
- Check selecting "Current No Reverse Brake ADC2" works as expected. Accelerating pressing throttle and braking using brake.

This seems just a wrong match between enum for control type and widgets representing ADC and ADC2:

Looking at enum definition:

```
    0        <enumNames>Off</enumNames>
    1        <enumNames>Current</enumNames>
    2        <enumNames>Current Reverse Center</enumNames>
    3        <enumNames>Current Reverse Button</enumNames>
    4        <enumNames>Current Reverse ADC2 Brake Button</enumNames>
    5        <enumNames>Current Reverse Button Brake Center</enumNames>
    6        <enumNames>Current No Reverse Brake Center</enumNames>
    7        <enumNames>Current No Reverse Brake Button</enumNames>
    8        <enumNames>Current No Reverse Brake ADC2</enumNames>
    9        <enumNames>Duty Cycle</enumNames>
    10      <enumNames>Duty Cycle Reverse Center</enumNames>
    11      <enumNames>Duty Cycle Reverse Button</enumNames>
    12      <enumNames>PID Speed</enumNames>
    13      <enumNames>PID Speed Reverse Center</enumNames>
    14      <enumNames>PID Speed Reverse Button</enumNames>
```

and code: https://github.com/vedderb/vesc_tool/blob/master/widgets/adcmap.cpp#L129-L155

```
void AdcMap::on_controlTypeBox_currentIndexChanged(int index)
{
    switch (index) {
    case 2: // Current Reverse Center
    case 4: // Current No Reverse Brake Center
    case 8: // Duty Cycle Reverse Center
        ui->displayCh1->setDual(true);
        break;

    case 0: // Off
    case 1: // Current
    case 3: // Current Reverse Button
    case 5: // Current No Reverse Brake Button
    case 6: // Current No Reverse Brake ADC2
    case 7: // Duty Cycle
    case 9: // Duty Cycle Reverse Button
        ui->displayCh1->setDual(false);
        break;

    default:
        break;
    }

    ui->displayCh1->setEnabled(index != 0);
    ui->displayCh2->setEnabled(index != 0);
    ui->displayCh2->setEnabled(index == 6);
}
```

Seems it is using and old definition:

```
    case 0: // Off
    case 1: // Current
    case 2: // Current Reverse Center
    case 3: // Current Reverse Button
    case 4: // Current No Reverse Brake Center
    case 5: // Current No Reverse Brake Button
    case 6: // Current No Reverse Brake ADC2
    case 7: // Duty Cycle
    case 8: // Duty Cycle Reverse Center
    case 9: // Duty Cycle Reverse Button
```

I don't understand all the modes, but probably can figure out a PR to fix most of them.

| old | new | type |
|------|-----|------|
| 0    |  0   | Off|
| 1    |  1   | Current|
| 2    |  2   | Current Reverse Center|
| 3    |  3   | Current Reverse Button|
| not exists | 4  | Current Reverse ADC2 Brake Button|
|  not exists | 5   | Current Reverse Button Brake Center|
| 4    |  6   | Current No Reverse Brake Center|
| 5    |  7   | Current No Reverse Brake Button|
| 6    |  8   | Current No Reverse Brake ADC2|
| 7    |  9   | Duty Cycle|
| 8    |  10   | Duty Cycle Reverse Center|
| 9    |  11   | Duty Cycle Reverse Button|
| not exists | 12  | PID Speed|
| not exists | 13  | PID Speed Reverse Center|
| not exists | 14  | PID Speed Reverse Button|

Probably your gently reminder to not use "magic" numbers on code.

**Comment by vedderb** [comment]
Thanks for the detailed description! I made a fix in the above commit, hope it works.
