### ISSUE TITLE
Move RT Data Logging to the Start page?

### ISSUE THREAD

**Issue by nitrousnrg** [vedderb/vesc_tool#119]
Datalogging is currently setup and activated from the last Developer page, but I think its a feature most users would like to use on a regular basis.

So how about moving the log directory path to the app settings and bringing the logging on/off to the front page?

![image](https://user-images.githubusercontent.com/309472/112835581-d852b280-906f-11eb-91fc-d4063194d2b8.png)

Also if the TCP server would be moved to settings we could remove the Developer page.

I can try making this change, but first I wanted to hear if it would be welcomed

Cheers

**Comment by danilolattaro** [comment]
I believe this one can now be closed.
