### ISSUE TITLE
Speed control PID noisy

### ISSUE THREAD

**Issue by ufechner7** [vedderb/vesc_tool#14]
All PID controllers lack a low pass filter for the D part (as far as I see). This is essential to get
a good response of the PID speed controller with low noise and low overshoot. Should be easy to implement.

**Comment by ufechner7** [comment]
Example code, that adds the filter parameter N:
```
FilterCoefficient = (Kd * u - Filter_DSTATE) * N;
    y = (Kp * u + Integrator_DSTATE) + FilterCoefficient;
    Integrator_DSTATE += Ki * u * 0.01;
    Filter_DSTATE += 0.01 * FilterCoefficient;
```

**Comment by vedderb** [comment]
This is something that should be in the firmware, not VESC Tool. It is added in one of the later versions though.
