### ISSUE TITLE
Do we need a new bootloader now?

### ISSUE THREAD

**Issue by surfdado** [vedderb/vesc_tool#206]
At what point will a new bootloader be required? For anyone using the official 5.3 release? Or only when using 6.0?

**Comment by surfdado** [comment]
Is this not the right forum to ask this kind of question? @vedderb?

**Comment by vedderb** [comment]
One comment: Since firmware 6 a bootloader with compression support has been required, so there were probably some issues in the transition. When the regular update is used the bootloader is updated automatically before VESC Tool updates the firmware.
