### ISSUE TITLE
SWD programmer VESC SIX MkV missing

### ISSUE THREAD

**Issue by Talabo** [vedderb/vesc_tool#208]
Hi!

While fixing a bricked VESC 6 MkV with another VESC (connecting with the SWD ports) I saw that in the SWD programmer under "included firmwares" the VESC 6 MkV (Mk5) was missing, and I only saw Mk4 and Mk3.

I fixed the VESC 6 MkV with Mk4 which makes the VESC Tool think it's a Mk4 after fixing the bricket VESC. I did a work-around by uploading a custom FW version which I have decleared for Mk5, so the VESC Tool knows it's a Mk5 and allowing me again to upload the original Mk5 FW version again through the normal procedure in VESC Tool.

For convenience the Mk5 should also be included in the "Included Firmwares"-list under SWD programmer.

**Comment by Teslafly** [comment]
is this fixed now?

**Comment by vedderb** [comment]
Should be fixed here:
https://github.com/vedderb/vesc_tool/commit/4ef8598dca3cfb014520ebb64efcbdde7f61508e
