### ISSUE TITLE
Battery default isn't sane

### ISSUE THREAD

**Issue by b264** [vedderb/vesc_tool#240]
The battery current defaults to 99A which isn't very sane.  Should it default to a much lower value (like 20A) and allow user to turn it up if they wish?

You don't want the least-savvy users (that haven't set the limits) running it the hardest, possibly having high failure rates, it does not lead to great user experience.

**Comment by TechAUmNu** [comment]
The defaults are defined by the default motor configuration on the individual esc.

**Comment by Teslafly** [comment]
should this be moved to the bldc fw repository? or just closed?

**Comment by TechAUmNu** [comment]
I would probably close this.
