### ISSUE TITLE
Where can I find PID position control from source code?

### ISSUE THREAD

**Issue by QZJGeorge** [vedderb/vesc_tool#241]
Hi,

I am trying add a current limit on the position PID controller to prevent my motor from jump start. Could someone show where this part of code is located? Thanks.

**Comment by Aquaharmonics** [comment]
Hi,

Not sure on the exact use case but have you tried changing the positive/negative ramp times?

**Comment by Teslafly** [comment]
What control input are you using? Ppm has safe start modes that should wait for the stick to be close to the motor position.

**Comment by Teslafly** [comment]
Logic for angle check before enabling motor found here: 

https://github.com/vedderb/bldc/blob/master/applications/app_ppm.c#L352

**Comment by Teslafly** [comment]
can this be closed?

**Comment by QZJGeorge** [comment]
Yes thanks please close it.

**Comment by Teslafly** [comment]
I can not close this. Only you, the issue creator, or the the project author/dev can close issues. You should have a button at the bottom of the page to close the issue.
