### ISSUE TITLE
Linux: no font directory warning from Qt

### ISSUE THREAD

**Issue by wilkinsw** [vedderb/vesc_tool#26]
The following warnings show up when running vesc from the command line:

```
QFontDatabase: Cannot find font directory /opt/Qt/5.9-static/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
```

Solution is to configure qt with `-feature-freetype -fontconfig` to allow the use of system fonts

**Comment by vedderb** [comment]
Using system fontconfig did not seem to work on older distributions with a static build done on a newer distribution, therefore the static build comes with built in fonts.

**Comment by StitchCookie** [comment]
How do I configure this on the command line.

**Comment by 82157402** [comment]
why close it？
