### ISSUE TITLE
Build  problems in gcc 12!!!

### ISSUE THREAD

**Issue by karu2003** [vedderb/vesc_tool#266]
cannot be Build with GCC 12.  in the new QT6.4.1 does not have a gamepad. 
"std::fill(std::begin(chain_sz), std::end(chain_sz), 0); " 
in GCC 12 do not support begin and end.

**Comment by Teslafly** [comment]
Vesc tool is currently only compatable with qt5.

I use qt 5.15.2 mingw 64-bit.

Though as far as I know what tool chain to use is not clarified. The readme.md does not contain a "compiling" section.

**Comment by Teslafly** [comment]
This probably fits into this issue:
https://github.com/vedderb/vesc_tool/issues/92
development documentation could be better.

Can this be closed?
