### ISSUE TITLE
not build in 32 bit

### ISSUE THREAD

**Issue by marcus7777** [vedderb/vesc_tool#27]
![screenshot from 2019-01-27 09-10-10](https://user-images.githubusercontent.com/6314260/51799087-aa198400-2214-11e9-96fe-c0ae19744053.png)

:-1: error: Unknown module(s) in QT: quickcontrols2

**Comment by vedderb** [comment]
At least Qt 5.9 is required for the QML stuff, and qt stopped making pre-built 32-bit x86 packages since version 5.6. You could build qt from source if you really need to. Have a look at the comments in the build_linux script. I haven't tested it though.
