### ISSUE TITLE
SIN/COS encoder parameters change not taken into account until reboot

### ISSUE THREAD

**Issue by totosolat** [vedderb/vesc_tool#277]
Hi,

I noticed that I need to reboot the board before the SIN/COS encoder parameters change take effect. (amplitudes, offsets)

Is there a reason for that? If not, I think it should be fixed. I could help on that if we agree on the expected behavior.

**Comment by Teslafly** [comment]
The expected behavior is for all parameters to take effect when mcconf parameters are written to the vesc. So yeah, this is probably a bug if reproducible.

**Comment by vedderb** [comment]
Should be fixed here
https://github.com/vedderb/bldc/commit/eade5ce18b60c1e51708466eadae9e705401ecb5

**Comment by totosolat** [comment]
Thanks a lot, I will test it soon and let you know!

**Comment by totosolat** [comment]
Hi,

I just tested, I can confirm the parameters are updating fine now.
Thanks!
