### ISSUE TITLE
VESC tool won't run input wizard after downgrading firmware through archive feature

### ISSUE THREAD

**Issue by jaykup26** [vedderb/vesc_tool#286]
If you use the new Firmware -> Archive feature to downgrade from 6.00 to 5.03 or older, the input wizard will not run when using the 6.00 tool.

![image](https://user-images.githubusercontent.com/628881/207631587-ddd1c506-fb70-4721-a8bc-06ecaf60b30c.png)

If this could work on at least firmware versions 5.01, 5.02 and 5.03 using the 6.00 tool or later, I think that would cover most use cases.

**Comment by vedderb** [comment]
I hope this fixes it:
https://github.com/vedderb/vesc_tool/commit/75c64a7e37221bd2b00323a358f7eed24a683318
The beta is building now, should be done any moment now if you want to try it out.

**Comment by jaykup26** [comment]
Tested and working great with latest commit https://github.com/vedderb/vesc_tool/commit/3540ae81cbcea9b85106dbe11f01c7bb0942d88e
