### ISSUE TITLE
Custom packages on mobile app

### ISSUE THREAD

**Issue by surfdado** [vedderb/vesc_tool#301]
Love seeing the package store working on iOS, thank you @Jfriesen222 
But while we're at it, would it also be possible to get support for loading custom package files on mobile?

**Comment by vedderb** [comment]
There is already support for that in the beta. It will be in the 6.02-release. You can click here and choose install from file
![image](https://user-images.githubusercontent.com/2311760/220175439-1eb9da8e-25e7-44c5-9393-d92134fa55ff.png)

**Comment by surfdado** [comment]
Awesome, sorry I couldn't test because I'm on iPhone. Didn't get a chance to try the beta APK yet.
