### ISSUE TITLE
Instant FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_2 on HW v4.12

### ISSUE THREAD

**Issue by lightseba** [vedderb/vesc_tool#32]
Upon flashing a v4.12 VESC (TORQUE ESC) with the 3.55 firmware, I get a red flashing light on startup. Typing `faults` into the console tells me there are no errors, but typing `fault` tells me FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_2. Since this was implemented in 3.55, I've reverted to 3.53 to resolve the issue.

**Comment by vedderb** [comment]
this should be fixed a few versions back
