### ISSUE TITLE
Dataloss when reopen and overwriting an existing .vescpkg file

### ISSUE THREAD

**Issue by Tomblarom** [vedderb/vesc_tool#335]
I just finished modifying an existing VESC package and it discarded all the made changes!
Under "Output" --> Choose file.. --> Selected existing .vescpkg --> confirmed override --> Save Package.

Its reproduceable. I expected the package to be overwritten and saved, instead of discarding my changes.. This is frustrating..

**Comment by vedderb** [comment]
It should save when selecting the file in the latest beta. Before it would just update the path box, but not save.

**Comment by Tomblarom** [comment]
Yes it saves now, but unfortunately it's not as intended. 😅 I was rather expecting the folder-icon to select an output path. Instead it loads the `test.vescpkg` and overwrites the contents in my newly written description field.

![image](https://github.com/vedderb/vesc_tool/assets/12703270/53810a31-ac2c-41f3-bcde-1f9e2fc0e088)

**Comment by vedderb** [comment]
I realized that it should not save the file actually, I removed that change again. The intention is that you can open a package you have been working on and continue working on it. So the first step would be to select the file you will be working with and then work on it and save the changes as you go. I will put some effort into that editor soon to make it a bit easier to use and understand.

**Comment by vedderb** [comment]
Hope this makes it more clear for now: https://github.com/vedderb/vesc_tool/commit/820f5e9d0706d9fc3de0fe4b64ce76debeee0761

**Comment by Tomblarom** [comment]
Perfect. This is more what a user would expect, when an overwrite is about to happen!
![image](https://github.com/vedderb/vesc_tool/assets/12703270/ffe81829-d095-4dbc-a5a1-2463ca590d19)

Beyond that wasn't finding any issues. Loading/saving works fine. Might give some feedback over here: https://github.com/vedderb/vesc_tool/issues/337
