### ISSUE TITLE
Feature Request: disable backup/restore buttons until package loading is completed

### ISSUE THREAD

**Issue by surfdado** [vedderb/vesc_tool#363]
When pressing the Backup button too soon after connecting then the package config won't be included. And there's no feedback to the user about this. A lot of new users are falling into this trap.

Easiest solution would be to simply disable backup/restore till package loading is completed.

**Comment by vedderb** [comment]
Something like this?
https://github.com/vedderb/vesc_tool/commit/a098ec641ec467dc478b979116c41a9103656696

**Comment by surfdado** [comment]
> Something like this? [a098ec6](https://github.com/vedderb/vesc_tool/commit/a098ec641ec467dc478b979116c41a9103656696)

What?? That was crazy fast. So awesome, thank you!!
