### ISSUE TITLE
Verify app on flathub

### ISSUE THREAD

**Issue by albfan** [vedderb/vesc_tool#368]
flathub request:

Create a page at https://vesc-project.com/.well-known/org.flathub.VerifiedApps.txt containing the following token:
9891ae39-999c-4825-9728-58f9903801b3

Example from gnome apps:

https://gnome.org/.well-known/org.flathub.VerifiedApps.txt

**Comment by vedderb** [comment]
Done! Can you see if it works?

**Comment by albfan** [comment]
Yes, it is verified on flathub developer portal. blue tick take some hours I think

Thanks!
