### ISSUE TITLE
USB connection with VESC on Android vesc tool

### ISSUE THREAD

**Issue by NormalHuman-Anything** [vedderb/vesc_tool#372]
I'm currently using mp2 with ninebot g30 dash on uart
I can't use ble module when dash is plugged in and dash doesn't have ble function(yet)
but I carry around type c to c cable with me so it'll be a great addition to be able to connect to vesc with usb c to c connector on mobile vesctool

**Comment by vedderb** [comment]
Last time I checked it was almost impossible to get USB working on android the way VESC Tool uses it. Unless Qt implements support for that I don't think this will happen any time soon unfortunately.
