### ISSUE TITLE
NRF52 firmware source? NRF52840 SKB501 module

### ISSUE THREAD

**Issue by Niuva** [vedderb/vesc_tool#40]
Seems like the provided firmware for NRF52840 uses a pin for RX (P0.11) that is not present on Skylab SKB501 modules. 
VESC Tool:
https://i.imgur.com/eO2bpxR.png

SKB501 Datasheet
http://www.skylab.com.cn/uploadfile/Download/Skylab_SKB501_V1.03_Datasheet.pdf

Could we perhaps get our hands on the source of the firmware? I'd love to tinker with it.
There are several modules on the market that use the NRF52840 chip and don't have the P0.11 pin exposed for DIY soldering.

Thanks! <3

**Comment by Teslafly** [comment]
Is this the fw source you are looking for?
https://github.com/vedderb/nrf51_vesc
Btw you may have to experiment with the different sdk versions. I don't think vedder specifies which version works and I forget which sdk kinda worked for me (16k ram builds failed) when I tried compiling.

**Comment by Niuva** [comment]
I'm afraid that's only for the NRF51 modules. I'm looking for the NRF52 code.
Benjamin has released a few pre-compiled ones, but no NRF52 source. Only the 51.
https://github.com/vedderb/vesc_tool/tree/master/res/other_fw

**Comment by vedderb** [comment]
I have a version with the NRF52 SDK as well, but haven't had an opportunity to clean it up and upload it yet. I will look into it soon and leave this issue open until then.

**Comment by vedderb** [comment]
Here is the NRF52 code:
https://github.com/vedderb/nrf52_vesc
There is some information in the readme, hopefully it is enough to get started with it.

**Comment by Niuva** [comment]
Thank you!
