### ISSUE TITLE
I can't communicate with the VEsc !

### ISSUE THREAD

**Issue by Savavit** [vedderb/vesc_tool#52]
When I received the FSESC 4.12 I connected it to the PC via USB, I updated the firmware and started the motor using the computer arrow buttons.

Today I tried to reconnect but the VESC Tool does not recognize the VESC.
The USB port is detected by Windows and when I remove power from the VESC I see that its USB port disappears from the management of Windows devices.
The COMM number is correct and the speed is at 115200.
But the VESC Tool does not communicate.  The message is:
Could not read firmware version. Make sure that the selected port really belongs to the VESC.

Please help me.

[Data.pdf](https://github.com/vedderb/vesc_tool/files/3793631/Data.pdf)

**Comment by DresnerRobotics** [comment]
This is intended for issues with the code, this is not an appropriate channel to ask for tech support. 

I would recommend going to one of the esk8 forums using these and asking for community support from there, you will get a better response. 

https://forum.esk8.news/

https://www.electric-skateboard.builders/
