### ISSUE TITLE
Precompiled linux binary from here fails immediately on finishing first-time-used intro

### ISSUE THREAD

**Issue by aabill2** [vedderb/vesc_tool#53]
Precompiled binary fails immediately on finishing the first-time-use intro. When run from a console I see:

symbol lookup error: ./vesc_tool_1.25: undefined symbol: DTLS_client_method, version OPENSSL_1.0.2

Could this be connected with change in 1.25 to static linking of open SSL lib? Platform is up-to-date OpenSUSE Tumbleweed. 

A binary compiled locally (which was straightforward within QtCreator once the needed additional Qt module devel files had been installed) starts and runs without problems.

Thanks
Bill

**Comment by vedderb** [comment]
This happens on ubuntu 19.10 too. I will look into it.

**Comment by vedderb** [comment]
This should be fixed with the latest build.
