### ISSUE TITLE
TCP connection support in mobile GUI

### ISSUE THREAD

**Issue by walmis** [vedderb/vesc_tool#56]
I'm using an esp8266 module for communicating with VESC. It makes sense to add such a feature inside the mobile GUI, since the implementation is already there.

I've made a quick and dirty patch for this on my branch:
https://github.com/walmis/vesc_tool/commit/fb94f8c6eca280a8405ce55ec42d4f47a267bbee#diff-d29046475a571f2dda6e687faa0c3f80

**Comment by vedderb** [comment]
Done a few versions ago.
