### ISSUE TITLE
WARNING (:0 ): BLE UART service not found

### ISSUE THREAD

**Issue by bj97301** [vedderb/vesc_tool#65]
I am getting this error when attempting to connect to my bluetooth module:
`WARNING (:0 ): BLE UART service not found`

I have tried on android, mac and linux.  I also have issues connecting from most apps(android and iOS).  The only app I was able to get working is xmatic on iOS:
https://apps.apple.com/us/app/xmatic-electric-skateboard/id1382937037

I have this bluetooth module: https://www.amazon.com/DSD-TECH-Bluetooth-iBeacon-Arduino/dp/B06WGZB2N4/ref=sr_1_3?keywords=HM-10+BLE+Bluetooth+4.0&qid=1583363125&sr=8-3

**Comment by vedderb** [comment]
VESC Tool only works with NRF5x ble modules with the correct firmware.
