### ISSUE TITLE
Window minimum width too large?

### ISSUE THREAD

**Issue by nitrousnrg** [vedderb/vesc_tool#80]
This is the silliest complain, but I can't find where can I fix it in the code.

In our dyno we are running 2 instances of vesc tool on the same monitor, and until very recently we could fit the 2 instances in the same screen:
![image](https://user-images.githubusercontent.com/309472/80553602-d89a8780-89a0-11ea-862d-81c29f0efc08.png)
But its not possible anymore.

Any clue if/where we can change this minimum size limit?

**Comment by vedderb** [comment]
Silly, but I agree :-) Fitting everything on a rather small screen, such as a raspberry pi or a tablet was always one of my goals. Fixed it in the latest version.
